language: r
cache: packages

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes

notifications:
  email:
    on_success: change
    on_failure: change
    
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
